### ISSUE TITLE
这个是否适合发布手机的webgl?

### ISSUE THREAD

**Issue by laoyuan1992** [Bian-Sh/Assemblies-Hotfix-Toolkit#3]
这个是否适合发布手机的webgl?

**Comment by Bian-Sh** [comment]
这个是一个编辑器辅助工具，是否支持 手机 webgl 完全看 aa是否支持，wolong 是否支持。
目前，我知道的是，aa 支持 webgl。
wolong 有限支持 webgl。
可以先去了解下 wolong（hybrid clr）

**Comment by Bian-Sh** [comment]
现在hybridclr支持了webgl 同时也支持微信小程序，你可以去关注下，这个 issue就结束了哈
