### ISSUE TITLE
大佬，打包出来后显示502，依赖错误，然后解决了这个错误又出了新问题

### ISSUE THREAD

**Issue by 3356550151** [Bian-Sh/Assemblies-Hotfix-Toolkit#4]
Unable to open archive file: D:/git/MeProject/Assemblies-Hotfix-Toolkit-Unity/Build/AA-Assemblies-Hotfix-Demo_Data/StreamingAssets/aa/StandaloneWindows64/hotfixassembliesgroup_assets_all_c5f3e802c094a365d08a6a475d1b5930.bundle

**Comment by Bian-Sh** [comment]
如果用 wolong 就先把 hybridclr_trial 跑通，然后看看 可寻址。
这个报错我没有遇到过，报错说的是 压缩包 打不开，呢也就是说有没有可能 AA 没有正常的完成打包呀
另外如果你用 wolong 最新版，我现在还没时间接入，你可以自己尝试着接入 ，需要处理元数据dll的预先加载哈。

**Comment by Bian-Sh** [comment]
现在hybridclr 自身安装工具很完备，可以自己写打包pipeline
没有后续反馈，先结束issue，按需开启哈
